[tools]
fzf = "latest"
jq = "latest"
eza = "latest"
bat = "latest"
fd = "latest"
ripgrep = "latest"
neovim = "latest"
tmux = "latest"
chezmoi = "latest"
go = "latest"
node = "lts"
yarn = "latest"
lazygit = "latest"
lazydocker = "latest"
docker-cli = "latest"
docker-compose = "latest"
kubectl = "latest"
k9s = "latest"

"npm:tree-sitter-cli" = "latest"
